# Generated by Django 4.1.3 on 2022-11-10 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address_Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('DOB', models.DateField(default=datetime.date.today)),
                ('Address', models.TextField(max_length=1000)),
                ('Pincode', models.TextField(max_length=10)),
            ],
        ),
    ]
