# Generated by Django 4.1.3 on 2022-11-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address_book',
            name='Address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='address_book',
            name='Pincode',
            field=models.TextField(max_length=255),
        ),
    ]
